// <auto-generated />
namespace SalesTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdtables));
        
        string IMigrationMetadata.Id
        {
            get { return "201612142053519_created tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
